# Setup
title:        Kevin Downs
description:      Hi, my name is Kevin Downs. I'm a software engineer by both trade and passion hailing from the South of Africa. I'm interested in all things technology, programming, and design. Below you'll find my ramblings and guides on topics such as .NET to databases and everything in between.
baseurl:      ""
paginate:     5
paginate_path: "/page/:num"

# About/contact
author:
  name:       Kevin Downs
  url:        https://kevindowns.co.za

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-minifier

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - deploy.bat

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge
show_drafts: false