# Setup
title:        Kevin Downs
tagline:      A personal technical blog about .NET to databases, and everything in between.
baseurl:      ""
paginate:     5

# About/contact
author:
  name:       Kevin Downs
  url:        https://kevindowns.co.za

# Gems
gems:
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - deploy.bat


markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge